spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.myshop.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#Í·Ïñ
comment.avatar: /images/avatar.png
